### ISSUE TITLE
Error on Ubuntu 16.04

### ISSUE THREAD

**Issue by fishouttah20** [chrisDeFouRire/sslping-cli#1]
Tried with and without port, tried simplifying password without special characters, etc, always the same error:

sslping-cli -u user@domain.com -p password domain.co.uk:443
/usr/local/lib/node_modules/sslping-cli/index.js:23
	[hostname, port] = host.split(':');
	^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by chrisDeFouRire** [comment]
I guess your node.js version (`node --version`) doesn't support ES2015 .

To upgrade to node v6 which is the new LTS version:

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

I've tried --harmony with 0.10, 0.12 and v4, but it doesn't have enough ES2015 support...
If you can't upgrade to v6, I'll try to babel-ify the CLI to ES5.

**Comment by chrisDeFouRire** [comment]
I've upgraded sslping-cli to 1.0.2 with support for node.js >= 0.10...

`npm uninstall -g sslping-cli` followed by `npm install -g sslping-cli` should make it work.

Sorry for the inconvenience, thank you for your patience !

**Comment by fishouttah20** [comment]
Thanks for the quick response. I did an uninstall, install and now get the below error message:
sslping-cli -u username@gmail.com -p password domain.com:443
/usr/local/lib/node_modules/sslping-cli/index.js:23
    hostname = _host$split2[0];
             ^

ReferenceError: hostname is not defined
    at /usr/local/lib/node_modules/sslping-cli/index.js:23:11
    at Array.map (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/sslping-cli/index.js:18:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

I went ahead and upgraded node per your above and that worked fine, will test it now, but wanted to get you the error before losing it.

**Comment by fishouttah20** [comment]
With Node version 6.9.1 I'm now getting:

/usr/local/lib/node_modules/sslping-cli/index.js:23
    hostname = _host$split2[0];
             ^

ReferenceError: hostname is not defined
    at /usr/local/lib/node_modules/sslping-cli/index.js:23:11
    at Array.map (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/sslping-cli/index.js:18:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

**Comment by chrisDeFouRire** [comment]
My bad... didn't test enough... 

I've just published a new version which I've tested with node 6.7. 

Thanks for your patience, nov 11 is a holiday here, I was too lazy ;-)

**Comment by chrisDeFouRire** [comment]
btw, it now works even with node 0.10

**Comment by fishouttah20** [comment]
don't waste your holiday on this, but for some reason, after an uninstall, reinstall, I'm still getting:

/usr/local/lib/node_modules/sslping-cli/index.js:23
    hostname = _host$split2[0];
             ^

ReferenceError: hostname is not defined
    at /usr/local/lib/node_modules/sslping-cli/index.js:23:11
    at Array.map (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/sslping-cli/index.js:18:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

I might try to download and use the source from github, seems like maybe npm isn't getting the latest code?

**Comment by fishouttah20** [comment]
well I did a git clone of the repo and then an npm install from the local folder and still got the same error. After a bit of friday night whiskey I'm in no shape to troubleshoot further. :)

**Comment by chrisDeFouRire** [comment]
I think the reinstall must have failed somewhere.
Can you try the following ?

```
chris@ubuntu:~$ node --version
v6.8.0
chris@ubuntu:~$ which sslping-cli
chris@ubuntu:~$ npm install -g sslping-cli
chris@ubuntu:~$ sudo npm install -g sslping-cli
chris@ubuntu:~$ sslping-cli -u <redacted> -p <redacted> sslping.com:443
Connected and authenticated
✓ sslping.com:443
```

`which` should return nothing, to confirm a previous sslping-cli isn't installed...
and it should all work just fine...

If you prefer to clone the project:

```
chris@ubuntu:~$ which sslping-cli
chris@ubuntu:~/tmp$ git clone https://github.com/chrisDeFouRire/sslping-cli.git
chris@ubuntu:~/tmp/sslping-cli$ npm install
chris@ubuntu:~/tmp/sslping-cli$ node index.js -u <redacted> -p <redacted> sslping.com:443
Connected and authenticated
✓ sslping.com:443
```

**Comment by fishouttah20** [comment]
I was naughty and ran npm with sudo to get rid of the error messages rather than setting it up so I didn't have to sudo. Was in a right mess where I couldn't uninstall sslping-cli. Running uninstall with or without sslping-cli gives me no output and which sslping-cli points to /usr/local/bin/sslping-cli.

I changed NPM so it's working directories were in my home directory, added it to my path, chown'd the npm folders to be owned by me, still had to manually delete the /usr/local/bin/sslping-cli file, and then was able to install sslping-cli without sudo, getting the new code, and it works like a champ importing things in bulk. 

Thanks!

**Comment by chrisDeFouRire** [comment]
some things you should know:
- the cli is designed to submit no more than 10 concurrent requests, to avoid overloading the server and timeout errors
- a load balancer is used in from of sslping processes, with IP affinity, so you can only saturate a single core on the server
- if you run the cli more than once concurrently, you risk having more timeout errors reported... However, the daily batch will spread the load uniformly, so this "problem" will occur only during import. The 10 concurrent requests limit is here to avoid timeouts

The React UI probably will need more work because you'll have _many_ servers shows on the same page... It's okay up to 100ish servers... after that it will become sluggish I'm afraid. I'll try to implement some kind of paging on the client to make it faster.

**Comment by fishouttah20** [comment]
No problem, it seems to be working well. Any preference on where/how I provide feedback and/or feature requests? Can do here, separate issue, multiple issues, email, etc.

The import bombed out after a few thousand, I can send full output via a private address (can DM to me). Something about unexpected JSON output.

If you're planning to build out the UI further, some suggestions include:
Ability to search/filter based on specific suffix - "domain" returns all domains with "domain" anywhere in the domain name, but would be nice to have "*.domain" where domain could only be at the end. Most won't have this issue because they can specify domain.com, but we have a gTLD and ".companyname" doesn't return just those TLDs.

Filtering by findings would be helpful. So show me all domains with SSLv3, etc.

I'm surprised the interface works at all with thousands of domains, so well impressed with the speed and performance of both the scan and GUI!
